### ISSUE TITLE
Differential Analyses - final.matrix 

### ISSUE THREAD

**Issue by Cmfffff** [eonurk/cinaR#7]
hello there,
cinaR is a wonderful tools for analysis ATAC-seq
I was wondering what  is format of final.matrix (Annotated Consensus peaks)
I was trying to conducting Differential Analyses in my custom peak matrix with custom annotation
and I want to conduct Differential Analyses only rather than cinaR
much appreciated if you can provide any information

**Comment by eonurk** [comment]
You could find more information about this in [Get Started](https://eonurk.github.io/cinaR/articles/cinaR.html) vignette.

Cheers, Onur

**Comment by Cmfffff** [comment]
thanks for your quick response
in the get started page, there is a original bed file that is unannotated
but it seems that  Annotated Consensus peaks file format that required for da is not present

**Comment by eonurk** [comment]
Yes, if you give cinaR the non-annotated matrix, it will create it for you in the final object

**Comment by Cmfffff** [comment]
exactly
but i now want to conduct differential analysis only as reference mentioned
`[da](https://eonurk.github.io/cinaR/reference/differentialAnalyses.html) 
i have a consensus peak set annotated by custom txdb so it doesn't match mm10 or hg19 …

the input of differential analysis is Annotated Consensus peaks i was confusing the format

**Comment by Cmfffff** [comment]
is the Annotated Consensus peaks format was bed-like, such counts of different groups in consensus peak set  with additional column that contain annotated information

**Comment by eonurk** [comment]
CinaR doesn't have support for other txdbs yet, but it would be awesome if you would like to contribute to the project!

**Comment by Cmfffff** [comment]
i checked the original code of cinaR.R
and solved the problem 
thanks again! it now support custom txdb
i would make it more elegant and commit~
